import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useEffect } from "react";


const FAKE_DATA = {
  result: true,
  data: [
    {
      id: 1234,
      name: "son heungmin",
      age: 31,
      hasPet: true,
      lists: ["hello", 123, true]
    },
    {
      id: 4614,
      name: "hwang heechan",
      age: 28,
      hasPet: true,
      lists: ["hello", 123, true]
    },
    {
      id: 4369,
      name: "kim minjae",
      age: 26,
      hasPet: false,
      lists: ["hello", 123, true]
    }
  ]
}

declare global {
  interface Window {
    Prism: {
      highlightAll: () => void;
    }
  }
}

const Home: NextPage = () => {
  const stringData = JSON.stringify(FAKE_DATA, null, 2)

  useEffect(() => {
    const { Prism } = window
    if (Prism != null) {
      Prism.highlightAll();
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.description}>
          <pre className="line-numbers" data-line="3,4">
            <code className=' language-json'>{stringData}</code>
          </pre>
          <hr />
          <pre>
            <code className=' language-js'>const a = () =&gt; 1;</code>
          </pre>
        </div>
      </main>
    </div>
  )
}

export default Home
